=== oszz/ox/ox-game-tools/conf/module/xsd/ox-template-1.0.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns= "http://www.ox.oszz.org/schema" 
	xmlns:xsd= "http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.ox.oszz.org/schema" 
    elementFormDefault="qualified" attributeFormDefault="unqualified">
 
 	<!-- 字符串 -->
    <xsd:simpleType name="str">
	  <xsd:restriction base="xsd:string" />
	</xsd:simpleType>
	
	<!-- Boolean型 -->
	<xsd:simpleType name="bool">
	  <xsd:restriction base="xsd:boolean" />
	</xsd:simpleType>
    
    <!-- Template元素的定义 -->
    <xsd:complexType name="templateComplexType">
      	<xsd:sequence>
      		<!-- 注释，必须有注释，最少最多只能有一个注释 -->
      		<xsd:element name="fields" type="fieldsComplexType" maxOccurs="1" minOccurs="0"/>
      	</xsd:sequence>
      	<!-- excel的名称，唯一 -->
    	<xsd:attribute name="name" type="xsd:ID" use="required"/>
    	<!-- 注释，必须有注释，最少最多只能有一个注释 -->
    	<xsd:attribute name="comments" type="str" use="required"/>
	</xsd:complexType>
	
	  <!-- 属性 元素的定义 -->
    <xsd:complexType name="fieldsComplexType">
      	<xsd:sequence>
      		<xsd:element name="field" type="str"  maxOccurs="unbounded" minOccurs="0"/>
      	</xsd:sequence>
	</xsd:complexType>
	 
	<xsd:complexType name="templatesComplexType">
      	<xsd:sequence>
      		<!-- 可以有无限多个Template -->
            <xsd:element name="template" type="templateComplexType" maxOccurs="unbounded" />
      	</xsd:sequence>
	</xsd:complexType>

	<!-- 整个模板的XML配置 -->	
	<xsd:element name="templates">  
       <xsd:complexType>  
         <xsd:sequence>  
         	<!-- 可以有无限多个Template -->
            <xsd:element name="template" type="templateComplexType" maxOccurs="unbounded" />
         </xsd:sequence>
      </xsd:complexType>
    </xsd:element>  
</xsd:schema>

=== oszz/ox/ox-game-tools/conf/template/templateData.xml
<?xml version="1.0" encoding="UTF-8" ?>
<templates xmlns= "http://www.ox.oszz.org/schema"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.ox.oszz.org/schema ox-template-1.0.xsd">  
    
    <template name="BattleBuff.xlsx" class="org.test.BattleBuffTemplate" isGenerator="true">
    	<comments>战斗Buff</comments>
    	<fields>
    		<field>buffName</field>
    		<field>buffType</field>
    		<field>continueType</field>
    		<field>buffID</field>
    	</fields>
    </template>
    
</templates>
